import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Movie App",
  description: "Generated by NEXTJS",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-black">
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
